import './global.css';
import { ReactQueryProvider } from '../lib/api/ReactQueryProvider';

export const metadata = {
  title: 'Welcome to org',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ReactQueryProvider>{children}</ReactQueryProvider>
      </body>
    </html>
  );
}
